# @package prototype_builder

_target_: methods.prototype.building.dbscan.DbscanPrototypeBuildStrategy
name: dbscan
eps_values: [0.05, 0.1, 0.15, 0.2, 0.25]
min_samples_values: [3, 5, 8]
search_sample_size: 3000
min_cluster_coverage: 0.6
random_state: 42
