// Generated by scripts/generate_family_extension_types.py.
// Do not edit this file manually.

export type FamilyAccessMode = "this_device_only";

export type FamilyAccessRole = "child" | "parent";

export interface FamilySetupStatusPayload {
  schema_version: string;
  access_mode: FamilyAccessMode;
  is_setup_complete: boolean;
  configured_roles: FamilyAccessRole[];
}

export interface FamilySetupRequestPayload {
  child_pin: string;
  parent_pin: string;
}

export interface FamilySetupResponsePayload {
  schema_version: string;
  access_mode: FamilyAccessMode;
  is_setup_complete: boolean;
  configured_roles: FamilyAccessRole[];
}

export interface FamilyUnlockRequestPayload {
  role: FamilyAccessRole;
  pin: string;
}

export interface FamilyUnlockResponsePayload {
  schema_version: string;
  role: FamilyAccessRole;
  granted: boolean;
  session_token: string | null;
  session_expires_at: string | null;
  remaining_attempts: number | null;
  locked_until: string | null;
}

export type ChildSupportAssistantMode = "local_guarded" | "local_llm" | "llm";

export type ChildSupportSafetyLevel = "supportive" | "check_in" | "parent_handoff" | "urgent";

export type ChildSupportScopeStatus = "in_scope" | "redirected";

export interface ChildSupportSuggestionPayload {
  id: string;
  label: string;
  prompt: string;
}

export interface ChildSupportConversationRequestPayload {
  message: string;
  conversation_id: string | null;
}

export interface ChildSupportConversationResponsePayload {
  schema_version: string;
  conversation_id: string;
  message_id: string;
  created_at: string;
  assistant_mode: ChildSupportAssistantMode;
  safety_level: ChildSupportSafetyLevel;
  scope_status: ChildSupportScopeStatus;
  reply_text: string;
  suggested_prompts: ChildSupportSuggestionPayload[];
  parent_handoff_suggested: boolean;
  parent_handoff_label: string | null;
  disclosure_notice: string;
}

export interface ChildSupportProactivePromptPayload {
  schema_version: string;
  should_prompt: boolean;
  safety_level: ChildSupportSafetyLevel | null;
  prompt_text: string | null;
  suggested_prompts: ChildSupportSuggestionPayload[];
}

export type WellbeingSignalLevel = "low" | "moderate" | "high" | "very_high";

export type WellbeingSignalTrend = "rising" | "steady" | "falling" | "volatile" | "unknown";

export type WellbeingSignalConfidence = "low" | "medium" | "high";

export type WellbeingSignalRange = "7d" | "14d" | "30d";

export interface WellbeingSignalSummaryPayload {
  schema_version: string;
  computed_at: string;
  signal_score: number;
  signal_level: WellbeingSignalLevel;
  signal_label: string;
  trend: WellbeingSignalTrend;
  summary: string;
  action_tip: string;
  confidence: WellbeingSignalConfidence;
  low_data: boolean;
}

export interface WellbeingSignalTimeseriesPointPayload {
  ts: string;
  signal_score: number;
}

export interface WellbeingSignalTimeseriesPayload {
  schema_version: string;
  computed_at: string;
  range: WellbeingSignalRange;
  points: WellbeingSignalTimeseriesPointPayload[];
}

export interface ParentUnlockRequestPayload {
  pin: string;
}

export interface ParentUnlockResponsePayload {
  schema_version: string;
  granted: boolean;
  session_token: string | null;
  session_expires_at: string | null;
  remaining_attempts: number | null;
  locked_until: string | null;
}
