// Generated by scripts/generate_family_extension_types.py.
// Do not edit this file manually.

export type WellbeingSignalLevel = "low" | "moderate" | "high" | "very_high";

export type WellbeingSignalTrend = "rising" | "steady" | "falling" | "volatile" | "unknown";

export type WellbeingSignalConfidence = "low" | "medium" | "high";

export type WellbeingSignalRange = "7d" | "14d" | "30d";

export interface WellbeingSignalSummaryPayload {
  schema_version: string;
  computed_at: string;
  signal_score: number;
  signal_level: WellbeingSignalLevel;
  signal_label: string;
  trend: WellbeingSignalTrend;
  summary: string;
  action_tip: string;
  confidence: WellbeingSignalConfidence;
  low_data: boolean;
}

export interface WellbeingSignalTimeseriesPointPayload {
  ts: string;
  signal_score: number;
}

export interface WellbeingSignalTimeseriesPayload {
  schema_version: string;
  computed_at: string;
  range: WellbeingSignalRange;
  points: WellbeingSignalTimeseriesPointPayload[];
}

export interface ParentUnlockRequestPayload {
  pin: string;
}

export interface ParentUnlockResponsePayload {
  schema_version: string;
  granted: boolean;
  session_token: string | null;
  session_expires_at: string | null;
  remaining_attempts: number | null;
  locked_until: string | null;
}
