// Generated by scripts/codegen/generate_family_extension_types.py.
// Do not edit this file manually.

export type FamilyAccessMode = "this_device_only";

export type FamilyAccessRole = "child" | "parent";

export interface FamilySetupStatusPayload {
  schema_version: string;
  access_mode: FamilyAccessMode;
  is_setup_complete: boolean;
  configured_roles: FamilyAccessRole[];
}

export interface FamilySetupRequestPayload {
  child_pin: string;
  parent_pin: string;
}

export interface FamilySetupResponsePayload {
  schema_version: string;
  access_mode: FamilyAccessMode;
  is_setup_complete: boolean;
  configured_roles: FamilyAccessRole[];
}

export interface FamilyUnlockRequestPayload {
  role: FamilyAccessRole;
  pin: string;
}

export interface FamilyUnlockResponsePayload {
  schema_version: string;
  role: FamilyAccessRole;
  granted: boolean;
  session_token: string | null;
  session_expires_at: string | null;
  remaining_attempts: number | null;
  locked_until: string | null;
}

export type ChildSupportAssistantMode = "local_guarded" | "local_llm" | "llm";

export type ChildSupportSafetyLevel = "supportive" | "check_in" | "parent_handoff" | "urgent";

export type ChildSupportScopeStatus = "in_scope" | "redirected";

export interface ChildSupportSuggestionPayload {
  id: string;
  label: string;
  prompt: string;
}

export interface ChildSupportConversationRequestPayload {
  message: string;
  conversation_id: string | null;
}

export interface ChildSupportConversationResponsePayload {
  schema_version: string;
  conversation_id: string;
  message_id: string;
  created_at: string;
  assistant_mode: ChildSupportAssistantMode;
  safety_level: ChildSupportSafetyLevel;
  scope_status: ChildSupportScopeStatus;
  reply_text: string;
  suggested_prompts: ChildSupportSuggestionPayload[];
  parent_handoff_suggested: boolean;
  parent_handoff_label: string | null;
  disclosure_notice: string;
}

export interface ChildSupportProactivePromptPayload {
  schema_version: string;
  should_prompt: boolean;
  safety_level: ChildSupportSafetyLevel | null;
  prompt_text: string | null;
  suggested_prompts: ChildSupportSuggestionPayload[];
}

export type WellbeingSignalLevel = "low" | "moderate" | "high" | "very_high";

export type WellbeingSignalTrend = "rising" | "steady" | "falling" | "volatile" | "unknown";

export type WellbeingSignalConfidence = "low" | "medium" | "high";

export type WellbeingSignalRange = "7d" | "14d" | "30d";

export interface WellbeingSignalSummaryPayload {
  schema_version: string;
  computed_at: string;
  signal_score: number;
  signal_level: WellbeingSignalLevel;
  signal_label: string;
  trend: WellbeingSignalTrend;
  summary: string;
  action_tip: string;
  confidence: WellbeingSignalConfidence;
  low_data: boolean;
}

export interface WellbeingSignalTimeseriesPointPayload {
  ts: string;
  signal_score: number;
}

export interface WellbeingSignalTimeseriesPayload {
  schema_version: string;
  computed_at: string;
  range: WellbeingSignalRange;
  points: WellbeingSignalTimeseriesPointPayload[];
}

export type WellbeingSpaceWebRelationType = "coactivation" | "transition";

export interface WellbeingSpaceWebNodePayload {
  id: string;
  label: string;
  intensity: number;
  level: WellbeingSignalLevel;
  trend: WellbeingSignalTrend;
  observed_event_count: number;
}

export interface WellbeingSpaceWebEdgePayload {
  source: string;
  target: string;
  weight: number;
  relation_type: WellbeingSpaceWebRelationType;
  evidence_count: number;
}

export interface WellbeingSpaceWebPayload {
  schema_version: string;
  computed_at: string;
  range: WellbeingSignalRange;
  strategy_name: string;
  strategy_version: string;
  nodes: WellbeingSpaceWebNodePayload[];
  edges: WellbeingSpaceWebEdgePayload[];
  low_data: boolean;
}

export interface ParentUnlockRequestPayload {
  pin: string;
}

export interface ParentUnlockResponsePayload {
  schema_version: string;
  granted: boolean;
  session_token: string | null;
  session_expires_at: string | null;
  remaining_attempts: number | null;
  locked_until: string | null;
}

export type TypingSegmentSourceType = "browser_extension" | "desktop_app" | "manual" | "unknown";

export type TypingSurfaceType = "input" | "textarea" | "contenteditable" | "rich_editor" | "unknown";

export type TypingCaptureConfidence = "high" | "medium" | "low";

export interface TypingSegmentStatsPayload {
  insert_count: number;
  delete_count: number;
  paste_count: number;
  composition_count: number;
}

export interface TypingSegmentPayload {
  schema_version: string;
  segment_id: string;
  source_type: TypingSegmentSourceType;
  surface_type: TypingSurfaceType;
  capture_confidence: TypingCaptureConfidence;
  page_origin: string | null;
  page_url: string | null;
  field_hint: string | null;
  started_at: string;
  ended_at: string;
  idle_ms: number;
  locale: string;
  final_text: string | null;
  deleted_text: string | null;
  stats: TypingSegmentStatsPayload;
}

export interface TypingSegmentIngestResponsePayload {
  schema_version: string;
  segment_id: string;
  query_id: string;
  top_category: string | null;
  top_score: number | null;
  message: string;
}

export interface TypingSegmentBatchIngestRequestPayload {
  segments: TypingSegmentPayload[];
}

export interface TypingSegmentBatchIngestResponsePayload {
  schema_version: string;
  processed: number;
  results: TypingSegmentIngestResponsePayload[];
}

export type CapturedTextSourceType = "search" | "reddit" | "webpage" | "typing" | "manual" | "unknown";

export type CapturedTextSurfaceType = "search_box" | "address_bar" | "reddit_post" | "reddit_comment" | "page_text" | "selection" | "typing_segment" | "unknown";

export interface CapturedTextEventPayload {
  schema_version: string;
  event_id: string;
  occurred_at: string;
  text: string;
  locale: string;
  source_type: CapturedTextSourceType;
  surface_type: CapturedTextSurfaceType;
  page_url: string | null;
  page_title: string | null;
  collector_version: string | null;
  metadata: Record<string, unknown>;
}

export interface CapturedTextBatchIngestRequestPayload {
  events: CapturedTextEventPayload[];
}

export interface CapturedTextIngestResponsePayload {
  schema_version: string;
  event_id: string;
  query_id: string;
  top_category: string | null;
  top_score: number | null;
  message: string;
}

export interface CapturedTextBatchIngestResponsePayload {
  schema_version: string;
  processed: number;
  results: CapturedTextIngestResponsePayload[];
}

export interface CapturedTextDebugJobRunRequestPayload {
  limit: number;
}

export interface CapturedTextDebugJobConfigRequestPayload {
  view_generation_enabled: boolean;
  view_generation_interval_seconds: number;
  view_generation_batch_size: number;
}

export interface CapturedTextDebugJobRunResultPayload {
  schema_version: string;
  selected_count: number;
  generated_count: number;
  failed_count: number;
  analysis_selected_count: number;
  analysis_processed_count: number;
  analysis_failed_count: number;
  pending_remaining_count: number;
  generated_view_count: number;
  message: string;
}

export interface CapturedTextDebugJobStatusPayload {
  schema_version: string;
  view_generation_enabled: boolean;
  view_generation_running: boolean;
  view_generation_interval_seconds: number;
  view_generation_batch_size: number;
  weak_text_provider_name: string;
  strong_text_provider_name: string;
  weak_text_identity_fallback: boolean;
  strong_text_identity_fallback: boolean;
  captured_text_event_count: number;
  generated_view_count: number;
  view_generation_status_counts: Record<string, number>;
  analysis_status_counts: Record<string, number>;
  last_run_at: string | null;
  last_run_result: CapturedTextDebugJobRunResultPayload | null;
}
