# @package _global_

query_data_sources:
  ourafla_reddit:
    labeled_jsonl: data/datasets/ourafla_mental_health/views/labeled1024_per_class_seed42_v1/backtranslation_nllb_en_de_fr_usb_v1/labeled_train.with_views.jsonl
    unlabeled_jsonl: data/datasets/ourafla_mental_health/views/labeled1024_per_class_seed42_v1/backtranslation_nllb_en_de_fr_usb_v1/unlabeled_pool.with_views.jsonl
    validation_jsonl: data/datasets/ourafla_mental_health/query_ssl/labeled1024_per_class_seed42_v1/validation.jsonl
    test_jsonl: data/datasets/ourafla_mental_health/query_ssl/labeled1024_per_class_seed42_v1/test.jsonl
  szegeelim_general4:
    labeled_jsonl: data/datasets/szegeelim_mental_health/views/labeled1024_per_class_seed42_v1/backtranslation_nllb_en_de_fr_usb_v1/labeled_train.with_views.jsonl
    unlabeled_jsonl: data/datasets/szegeelim_mental_health/views/labeled1024_per_class_seed42_v1/backtranslation_nllb_en_de_fr_usb_v1/unlabeled_pool.with_views.jsonl
    validation_jsonl: data/datasets/szegeelim_mental_health/query_ssl/labeled1024_per_class_seed42_v1/validation.jsonl
    test_jsonl: data/datasets/szegeelim_mental_health/query_ssl/labeled1024_per_class_seed42_v1/test.jsonl

query_data_selection:
  labeled: ourafla_reddit
  unlabeled: ourafla_reddit
  validation: ourafla_reddit
  test: ourafla_reddit

query_source:
  name: labeled_${query_data_selection.labeled}_unlabeled_${query_data_selection.unlabeled}_validation_${query_data_selection.validation}_test_${query_data_selection.test}
  train_jsonl: ${query_data_sources.${query_data_selection.labeled}.labeled_jsonl}
  unlabeled_jsonl: ${query_data_sources.${query_data_selection.unlabeled}.unlabeled_jsonl}
  validation_jsonl: ${query_data_sources.${query_data_selection.validation}.validation_jsonl}
  test_jsonl: ${query_data_sources.${query_data_selection.test}.test_jsonl}

train_jsonl: ${query_source.train_jsonl}
unlabeled_jsonl: ${query_source.unlabeled_jsonl}
query_data_selection_slug: labeled-${query_data_selection.labeled}_unlabeled-${query_data_selection.unlabeled}_validation-${query_data_selection.validation}_test-${query_data_selection.test}
